// Mocks generated by Mockito 5.1.0 from annotations
// in creating_mocks/test/mockito/random_user_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:creating_mocks/remote_datasource.dart' as _i2;
import 'package:creating_mocks/user_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i2.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserModel?> getRandomUser() =>
      (super.noSuchMethod(Invocation.method(#getRandomUser, []),
              returnValue: Future<_i4.UserModel?>.value())
          as _i3.Future<_i4.UserModel?>);
}
